export const configFileName: string = 'spe.config.json';

export const readonlyComment: string = `/**
 * This code was auto generated by 'sp-entity'
 * Changes made to this file may be lost
 */

// tslint:disable`;

export const readonlyCommentWithEdit: string = `/**
 * This code was auto generated by 'sp-entity'
 * Changes made to this file may be lost, edit '[FILENAME]' instead
 */

// tslint:disable`;

export const editComment: string = `/**
 * This code was auto generated by 'sp-entity'
 * You may add/edit field mappings in this file then re-run 'spe' tool to automatically update related interfaces
 */

// tslint:disable`;
